// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PCM.Cocina.WebApp3.Controllers
{
    public partial class MenuController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MenuController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CrearMenu()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CrearMenu);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MenuController Actions { get { return MVC.Menu; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Menu";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Menu";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ListaMenus = "ListaMenus";
            public readonly string RegistrarMenu = "RegistrarMenu";
            public readonly string ListarMenus = "ListarMenus";
            public readonly string CrearMenu = "CrearMenu";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ListaMenus = "ListaMenus";
            public const string RegistrarMenu = "RegistrarMenu";
            public const string ListarMenus = "ListarMenus";
            public const string CrearMenu = "CrearMenu";
        }


        static readonly ActionParamsClass_ListarMenus s_params_ListarMenus = new ActionParamsClass_ListarMenus();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListarMenus ListarMenusParams { get { return s_params_ListarMenus; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListarMenus
        {
            public readonly string jtStartIndex = "jtStartIndex";
            public readonly string jtPageSize = "jtPageSize";
            public readonly string jtSorting = "jtSorting";
            public readonly string texto = "texto";
        }
        static readonly ActionParamsClass_CrearMenu s_params_CrearMenu = new ActionParamsClass_CrearMenu();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CrearMenu CrearMenuParams { get { return s_params_CrearMenu; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CrearMenu
        {
            public readonly string nombreMenu = "nombreMenu";
            public readonly string cbEntrada1 = "cbEntrada1";
            public readonly string cbEntrada2 = "cbEntrada2";
            public readonly string cbPlatoDeFondo1 = "cbPlatoDeFondo1";
            public readonly string cbPlatoDeFondo2 = "cbPlatoDeFondo2";
            public readonly string cbRefresco = "cbRefresco";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string ListaMenus = "ListaMenus";
                public readonly string RegistrarMenu = "RegistrarMenu";
            }
            public readonly string Index = "~/Views/Menu/Index.cshtml";
            public readonly string ListaMenus = "~/Views/Menu/ListaMenus.cshtml";
            public readonly string RegistrarMenu = "~/Views/Menu/RegistrarMenu.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_MenuController : PCM.Cocina.WebApp3.Controllers.MenuController
    {
        public T4MVC_MenuController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ListaMenusOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListaMenus()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListaMenus);
            ListaMenusOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegistrarMenuOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RegistrarMenu()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RegistrarMenu);
            RegistrarMenuOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ListarMenusOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int jtStartIndex, int jtPageSize, string jtSorting, string texto);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListarMenus(int jtStartIndex, int jtPageSize, string jtSorting, string texto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListarMenus);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jtStartIndex", jtStartIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jtPageSize", jtPageSize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jtSorting", jtSorting);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "texto", texto);
            ListarMenusOverride(callInfo, jtStartIndex, jtPageSize, jtSorting, texto);
            return callInfo;
        }

        [NonAction]
        partial void CrearMenuOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string nombreMenu, int cbEntrada1, int cbEntrada2, int cbPlatoDeFondo1, int cbPlatoDeFondo2, int cbRefresco);

        [NonAction]
        public override System.Web.Mvc.ActionResult CrearMenu(string nombreMenu, int cbEntrada1, int cbEntrada2, int cbPlatoDeFondo1, int cbPlatoDeFondo2, int cbRefresco)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CrearMenu);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nombreMenu", nombreMenu);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "cbEntrada1", cbEntrada1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "cbEntrada2", cbEntrada2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "cbPlatoDeFondo1", cbPlatoDeFondo1);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "cbPlatoDeFondo2", cbPlatoDeFondo2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "cbRefresco", cbRefresco);
            CrearMenuOverride(callInfo, nombreMenu, cbEntrada1, cbEntrada2, cbPlatoDeFondo1, cbPlatoDeFondo2, cbRefresco);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
